# Generated by Django 4.0.5 on 2024-11-13 18:38

import FilkaRecepty.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodTag', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_folder', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=FilkaRecepty.models.get_upload_path, verbose_name='Food image')),
                ('position', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=500)),
                ('position', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=60)),
                ('position', models.DecimalField(decimal_places=0, max_digits=10)),
                ('ingredientName', models.ManyToManyField(related_name='ingredientName', to='FilkaRecepty.ingredient')),
                ('units', models.ManyToManyField(related_name='units', to='FilkaRecepty.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('date', models.DateTimeField()),
                ('foodTags', models.ManyToManyField(related_name='foodTags', to='FilkaRecepty.foodtags')),
                ('images', models.ManyToManyField(related_name='images', to='FilkaRecepty.imagefood')),
                ('ingredients', models.ManyToManyField(related_name='ingredients', to='FilkaRecepty.ingredients')),
                ('steps', models.ManyToManyField(related_name='steps', to='FilkaRecepty.steps')),
            ],
        ),
    ]
