# Generated by Django 4.0.5 on 2024-11-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilkaRecepty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images', to='FilkaRecepty.imagefood'),
        ),
    ]
