# Generated by Django 4.2.17 on 2026-02-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilkaRecepty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagGroup', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='foodtags',
            name='tagGroup',
            field=models.ManyToManyField(related_name='tagGroups', to='FilkaRecepty.taggroups'),
        ),
    ]
