# Generated by Django 4.2.17 on 2025-09-25 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FilkaRecepty', '0002_passwordreset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='images',
        ),
        migrations.AddField(
            model_name='imagefood',
            name='food',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='FilkaRecepty.foods'),
            preserve_default=False,
        ),
    ]
