# Generated by Django 4.0.5 on 2024-12-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilkaRecepty', '0002_alter_foods_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='foods',
            name='urls',
            field=models.ManyToManyField(related_name='urls', to='FilkaRecepty.url'),
        ),
    ]
