# Generated by Django 4.2.17 on 2026-02-01 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FilkaRecepty', '0002_taggroups_foodtags_taggroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggroups',
            old_name='tagGroup',
            new_name='groupName',
        ),
        migrations.RemoveField(
            model_name='foodtags',
            name='tagGroup',
        ),
        migrations.AddField(
            model_name='foodtags',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_tags', to='FilkaRecepty.taggroups'),
        ),
    ]
