# Generated by Django 4.2.17 on 2025-09-27 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FilkaRecepty', '0003_remove_foods_images_imagefood_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='steps',
        ),
        migrations.AddField(
            model_name='steps',
            name='food',
            field=models.ForeignKey(default=59, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='FilkaRecepty.foods'),
            preserve_default=False,
        ),
    ]
