# Generated by Django 4.0.5 on 2024-12-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilkaRecepty', '0003_url_foods_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='urls',
            field=models.ManyToManyField(blank=True, related_name='urls', to='FilkaRecepty.url'),
        ),
    ]
