# Generated by Django 4.2.17 on 2026-02-01 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FilkaRecepty', '0003_rename_taggroup_taggroups_groupname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtags',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food_tags', to='FilkaRecepty.taggroups'),
            preserve_default=False,
        ),
    ]
