# Generated by Django 4.2.17 on 2026-02-01 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FilkaRecepty', '0004_alter_foodtags_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtags',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_tags', to='FilkaRecepty.taggroups'),
        ),
    ]
