# Generated by Django 4.0.5 on 2024-12-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilkaRecepty', '0004_alter_foods_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='step',
            field=models.CharField(max_length=1500),
        ),
    ]
