# Generated by Django 4.2.17 on 2025-09-28 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FilkaRecepty', '0004_remove_foods_steps_steps_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='urls',
        ),
        migrations.AddField(
            model_name='url',
            name='food',
            field=models.ForeignKey(default=60, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='FilkaRecepty.foods'),
            preserve_default=False,
        ),
    ]
